services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psychology
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - psychology_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s

  web:
    image: psychology-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: api_container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - psychology_net

volumes:
  postgres_data:

networks:
  psychology_net:
    driver: bridge
