version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psychology
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - psychology_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    image: psychology-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: api_container
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app/data/situational:/app/app/data/situational
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/psychology
    networks:
      - psychology_net

volumes:
  postgres_data:

networks:
  psychology_net:
    driver: bridge
